version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: portfolio-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
    environment:
      - MONGO_INITDB_DATABASE=portfolio
    restart: unless-stopped
    networks:
      - portfolio-network

  mongo-express:
    image: mongo-express:latest
    container_name: portfolio-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - portfolio-network

volumes:
  mongo_data_dev:

networks:
  portfolio-network:
    driver: bridge