version: "3.8"

services:
  app:
    build: .
    container_name: portfolio-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB=mongodb://mongo:27017/portfolio
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-2024
      - FRONTEND_URL=http://localhost:5000
      - BASE_URL=http://localhost:5000
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/projects"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:6.0
    container_name: portfolio-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./backups:/data/backup
    environment:
      - MONGO_INITDB_DATABASE=portfolio
    restart: unless-stopped
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo_data:

networks:
  portfolio-network:
    driver: bridge

