services:
  - type: web
    name: portfolio-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile

  - type: cron
    name: seed-db
    schedule: "@once"
    envVars:
      - key: NODE_ENV
        value: production
    dockerfilePath: ./Dockerfile
    startCommand: npm run seed-all
